name: Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.8

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: saleor
          POSTGRES_USER: saleor
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install system dependencies
      run: apt-get install libpq-dev

    - name: Install dependencies
      run: python -m pip install -r requirements_dev.txt

    - name: Run tests
      run: pytest --cov --junitxml=junit/test-results.xml
      env:
        DATABASE_URL: "postgres://saleor:saleor@postgres:5432/saleor"

    - uses: codecov/codecov-action@v1

    - uses: actions/upload-artifact@v1
      with:
        name: pytest-results
        path: junit/test-results.xml
      if: ${{ always() }}
